### ISSUE TITLE
Crashing  (ForgeCraft is the cause and needs update) 

### ISSUE THREAD

**Issue by Xelbayria** [kitsushadow/forgecraft-issues#10]
PrimalCore-1.12.2-0.6.105
ForgeCraft-1.6.51
forge-14.23.5.2854

These are the latest version I am using and there's no other mods involved. This confirmed that there is an issue with ForgeCraft

---- Minecraft Crash Report ----
// You're mean.

Time: 5/7/20 1:06 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Kitsu's Forgecraft (forgecraft)
Caused by: java.lang.VerifyError: Bad access to protected data in getfield
Exception Details:
  Location:
    nmd/primal/forgecraft/blocks/Chisel.doDamaging(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/entity/player/EntityPlayer;)V @25: getfield
  Reason:
    Type 'net/minecraft/util/math/BlockPos' (current frame, stack[1]) is not assignable to 'nmd/primal/forgecraft/blocks/Chisel'
  Current Frame:
    bci: @25
    flags: { }
    locals: { 'nmd/primal/forgecraft/blocks/Chisel', 'net/minecraft/world/World', 'net/minecraft/util/math/BlockPos', 'net/minecraft/block/state/IBlockState', 'net/minecraft/entity/player/EntityPlayer' }
    stack: { float }
  Bytecode:
    0x0000000: 2db9 0107 0100 b201 deb6 01ed 9a00 312b
    0x0000010: 2cb6 018c b901 0701 00b4 01fe 0b95 9e00
    0x0000020: 1f2b 1904 b601 f4b8 014d 1064 b601 f764
    0x0000030: 2cb8 014d 0610 0ab6 0182 b601 fbb1     
  Stackmap Table:
    same_frame(@61)

	at nmd.primal.forgecraft.init.ModBlocks.init(ModBlocks.java:65)
	at nmd.primal.forgecraft.ForgeCraft.preInit(ForgeCraft.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 444990832 bytes (424 MB) / 1180696576 bytes (1126 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version      | Source                        | Signature                                |
	|:----- |:---------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCH   | minecraft  | 1.12.2       | minecraft.jar                 | None                                     |
	| LCH   | mcp        | 9.42         | minecraft.jar                 | None                                     |
	| LCH   | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge      | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | primal     | 0.6.105      | PrimalCore-1.12.2-0.6.105.jar | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| LCE   | forgecraft | 1.6.51       | ForgeCraft-1.6.51.jar         | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.92' Renderer: 'GeForce GTX 1070/PCIe/SSE2'

**Comment by kitsushadow** [comment]
Add Craft tweaker

**Comment by Xelbayria** [comment]
I see. You should add that information to the description. "required CraftTweaker". That will do for now.  But you should update your mod that it's not dependent on Crafttweaker mod. 

and how do you add the "spoiler" feature? I noticed the "..."

**Comment by kitsushadow** [comment]
Its a bug. I didn't actually code it as a requirement.

**Comment by Xelbayria** [comment]
I know that you didn't code it to make it dependent on the mod. I can tell it's a bug.

**Comment by Xelbayria** [comment]
Okay, I got a new report... There is a conflict between two mods: 
PrimalCore/Kitsu's ForgeCraft and TerrafirmaCraft:
https://pastebin.com/QxVLyE7T
these mods are the cause of the crash, when Minecraft is about to finish the third stage: Initializing 

This will be a good reason for you to update your mod, I hope this helps you investigate more and improve your mods.

**Comment by kitsushadow** [comment]
It loads without Terriferma?

**Comment by Xelbayria** [comment]
Yes, it loaded fine without TFC. It's the same for TFC without PC/KFC. so that means conflict.

**Comment by kitsushadow** [comment]
Sure, i wasn't able to tell much of anything from that pastebin though.

**Comment by Xelbayria** [comment]
damn. I really like PrimalCore and Kitsu's FC, these are only one that I liked for a blacksmith mod. With this conflict. :(  I was hoping that it would help you with the conflict. 

Edit: I guess I'll have to report this to the TFC staff. Hoping that they can do something about this

**Comment by kitsushadow** [comment]
If there was more in the stacktrace maybe I could offer more assistance.
Conflicts are tricky. We also have folks in our discord who you can tap
into and provide assistance.

**Comment by Xelbayria** [comment]
Indeed, I knew it was very tricky. that's one of the worst I disliked about programming and language coding. I have basic knowledge about programming and I'll do more studying to gain knowledge. 

I'll go to the discord but there's no guarantee that I can get some solution

**Comment by Xelbayria** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/381

check this out, there's more information about why they had a conflict, it has to do with minecraft:torch

Edit: relating PrimalCore
https://github.com/An-Sar/PrimalCore/issues/350

Edit 2: 
alright, I found a temporary solution that can make these mods work together for now. so I'll close this issue for now. 
SOLUTION:
You only need to toggle/disable in PrimalCore => B:REPLACE_VANILLA_TORCHES=true (change it to false)

I hope you find a way to fix this register issue between these two mods to solve the conflict.

**Comment by kitsushadow** [comment]
Its probably conflicting with primal then
