### ISSUE TITLE
NoClassDefFoundError on a PrimalCore class

### ISSUE THREAD

**Issue by Hallowizer** [kitsushadow/forgecraft-issues#3]
Hi! I'm using the latest Kitsu's Forgecraft, and the latest PrimalCore, as of July 17, 2019. When I launch the game, I get this error:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.59-core.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  LoadingPlugin (BetterWithLib-1.12-1.5.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/17/19 6:00 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: nmd/primal/core/common/recipes/tile/CauldronRecipe
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: nmd/primal/core/common/recipes/tile/CauldronRecipe
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:93)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 36 more
Caused by: java.lang.ClassNotFoundException: nmd.primal.core.common.recipes.tile.CauldronRecipe
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.5
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1333076488 bytes (1271 MB) / 1919418368 bytes (1830 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 3 total; -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 64 mods loaded, 64 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                               | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                         | 1.12.2                   | minecraft.jar                                        | None                                     |
	| LC    | mcp                               | 9.42                     | minecraft.jar                                        | None                                     |
	| LC    | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                             | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | applecore                         | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                         | None                                     |
	| LC    | crafttweaker                      | 4.1.19                   | CraftTweaker2-1.12-4.1.19.jar                        | None                                     |
	| LC    | mtlib                             | 3.0.6                    | MTLib-3.0.6.jar                                      | None                                     |
	| LC    | modtweaker                        | 4.0.17                   | modtweaker-4.0.17.jar                                | None                                     |
	| LC    | jei                               | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                            | None                                     |
	| LC    | ctm                               | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                            | None                                     |
	| LC    | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                             | None                                     |
	| LC    | chisel                            | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                         | None                                     |
	| LC    | endercore                         | 1.12.2-0.5.59            | EnderCore-1.12.2-0.5.59.jar                          | None                                     |
	| LC    | enderio                           | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LC    | enderiointegrationtic             | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LC    | tconstruct                        | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                     | None                                     |
	| LC    | immersiveengineering              | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LC    | betterwithmods                    | 1.12-2.3.20-1027         | BetterWithMods-1.12-2.3.20-1027.jar                  | None                                     |
	| LC    | appleskin                         | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                           | None                                     |
	| LC    | base                              | 3.13.0                   | base-1.12.2-3.13.0.jar                               | None                                     |
	| LC    | betterwithlib                     | ${version}               | BetterWithLib-1.12-1.5.jar                           | None                                     |
	| LC    | blockdrops                        | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                          | None                                     |
	| LC    | ceramics                          | 1.12-1.3.7               | Ceramics-1.12-1.3.7.jar                              | None                                     |
	| LC    | contenttweaker                    | 1.12.2-4.9.1             | ContentTweaker-1.12.2-4.9.1.jar                      | None                                     |
	| LC    | conarm                            | 1.2.4                    | conarm-1.12.2-1.2.4.jar                              | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LC    | controlling                       | 3.0.7                    | Controlling-3.0.7.jar                                | None                                     |
	| LC    | craftingtweaks                    | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                      | None                                     |
	| LC    | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.19.jar                        | None                                     |
	| LC    | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.19.jar                        | None                                     |
	| LC    | custombars                        | 1.1                      | custombars-1.1.jar                                   | None                                     |
	| LC    | enderiobase                       | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LC    | enderioconduits                   | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LC    | enderioconduitsappliedenergistics | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LC    | enderioconduitsopencomputers      | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LC    | enderioconduitsrefinedstorage     | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LC    | enderiointegrationforestry        | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LC    | enderiointegrationticlate         | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LC    | ftblib                            | 5.4.3.129                | FTBLib-5.4.3.129.jar                                 | None                                     |
	| LC    | enderiomachines                   | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LC    | enderiopowertools                 | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                            | None                                     |
	| LC    | forgelin                          | 1.8.3                    | Forgelin-1.8.3.jar                                   | None                                     |
	| LC    | exnihilocreatio                   | 1.12.2-0.4               | exnihilocreatio-1.12.2-0.4.jar                       | None                                     |
	| LC    | excompressum                      | 3.0.31                   | ExCompressum_1.12.2-3.0.31.jar                       | None                                     |
	| LC    | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.9.jar                           | None                                     |
	| LC    | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                          | None                                     |
	| LC    | primal                            | 0.6.105                  | PrimalCore-1.12.2-0.6.105.jar                        | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| LE    | forgecraft                        | 1.6.5                    | ForgeCraft-1.6.5.jar                                 | None                                     |
	| L     | itemfilters                       | 1.0.3.12                 | ItemFilters-1.0.3.12.jar                             | None                                     |
	| L     | ftbquests                         | 1.7.2.187                | FTBQuests-1.7.2.187.jar                              | None                                     |
	| L     | horsepower                        | 2.6.4                    | HorsePower-1.12.2-2.6.4.74.jar                       | None                                     |
	| L     | inspirations                      | 1.12.2-0.2.4             | Inspirations-1.12.2-0.2.4.jar                        | None                                     |
	| L     | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                             | None                                     |
	| L     | radixcore                         | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-universal.jar                 | None                                     |
	| L     | mca                               | 1.12.2-5.3.1             | MCA-1.12.x-5.3.1-universal.jar                       | None                                     |
	| L     | mousetweaks                       | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                        | None                                     |
	| L     | harvestcraft                      | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zd Surprise for Yogcast.jar | None                                     |
	| L     | placebo                           | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                             | None                                     |
	| L     | scavenge                          | 1.8                      | Scavenge V1.12-1.8.3.2.jar                           | None                                     |
	| L     | tcomplement                       | 1.12.2-0.4.2             | TinkersComplement-1.12.2-0.4.2.jar                   | None                                     |
	| L     | tinkersjei                        | 1.2                      | tinkersjei-1.2.jar                                   | None                                     |
	| L     | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                  | None                                     |
	| L     | voidislandcontrol                 | 1.5.3                    | voidislandcontrol-1.5.3.jar                          | None                                     |
	| L     | hungeroverhaul                    | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar           | None                                     |
	| L     | primal_tech                       | 0.3.4                    | PrimalTech-0.3.4.jar                                 | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
EnderCorePlugin (EnderCore-1.12.2-0.5.59-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (BetterWithLib-1.12-1.5.jar)
  betterwithmods.library.core.ClassTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-12.9.22' Renderer: 'Intel(R) UHD Graphics 630'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)
```

When I remove Forgecraft from the pack, the error goes away, so I believe it is coming from this mod. Can someone take a look?

**Comment by kitsushadow** [comment]
Upgrading your Primalcore version will resolve this.
